name: apsc
type: drupal10
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
disable_settings_management: true # @see web/sites/default/docker.settings.php
nodejs_version: 18
database:
  type: mysql
  version: 8.0
web_environment:
- DRUSH_OPTIONS_URI=https://aspc.ddev.site
